version: 2.1

jobs:

  print-pipeline-info:
    docker: 
      - image: circleci/node:latest
    steps:
      - run: echo "Pipeline Id:<< pipeline.id >>"
      - run: echo "Pipeline Number:<< pipeline.number >>"
      - run: echo "Pipeline Git project url:<< pipeline.project.git_url >>"
      - run: echo "Pipeline Project type:<< pipeline.project.git_url >>"
      - run: echo "Pipeline Git branch:<< pipeline.git.branch >>"

  print-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"
  

  print-world:
    docker: 
      - image: circleci/node:latest    
    steps:
      - checkout
      - run:
          name: "Say World"
          command: "echo World Mr. $MY_NAME_IN_ENV_VAR"


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - print-pipeline-info
      - print-hello
      - print-world:
          requires: 
            - print-hello
